services:
  openvpn:
    image: kylemanna/openvpn:latest
    container_name: openvpn-server
    ports:
      - "${OPENVPN_PORT:-1194}:1194/udp"
    volumes:
      - openvpn-data:/etc/openvpn
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    environment:
      - EASYRSA_BATCH=1
    networks:
      - openvpn-network

networks:
  openvpn-network:
    driver: bridge

volumes:
  openvpn-data:
    driver: local