services:
  openvpn:
    image: kylemanna/openvpn:latest
    container_name: openvpn-server
    networks:
      - openvpn-network
    ports:
      - "${OPENVPN_PORT:-1194}:${OPENVPN_PORT:-1194}/${OPENVPN_PROTOCOL:-udp}"
    volumes:
      - openvpn-data:/etc/openvpn
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pgrep openvpn || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.5'
        reservations:
          memory: 128M
          cpus: '0.25'
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: 3
    environment:
      - EASYRSA_BATCH=1
      - OPENVPN_PROTOCOL=${OPENVPN_PROTOCOL:-udp}
      - OPENVPN_PORT=${OPENVPN_PORT:-1194}
      - VPN_NETWORK=${VPN_NETWORK:-10.8.0.0}
      - VPN_SERVER_IP=${VPN_SERVER_IP:-10.8.0.1}
      - VPN_DOMAIN=${VPN_DOMAIN:-vpn.example.com}
      - TUN_DEVICE_NAME=${TUN_DEVICE_NAME:-tun0}
      - ENABLE_COMPRESSION=${ENABLE_COMPRESSION:-false}
      - ALLOW_DUPLICATE_CN=${ALLOW_DUPLICATE_CN:-false}

networks:
  openvpn-network:
    driver: bridge
    name: openvpn-network

volumes:
  openvpn-data:
    name: openvpn-data
    driver: local