version: '3.8'

services:
  openvpn:
    image: kylemanna/openvpn:latest
    container_name: openvpn-server
    ports:
      - "${OPENVPN_PORT:-1194}:1194/${OPENVPN_PROTOCOL:-udp}"
    volumes:
      - openvpn-data:/etc/openvpn
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    sysctls:
      - net.ipv6.conf.default.forwarding=1
      - net.ipv6.conf.all.forwarding=1
    restart: unless-stopped
    extra_hosts:
      - "docker-host:host-gateway"
    environment:
      - EASYRSA_BATCH=1
      - OPENVPN_PROTOCOL=${OPENVPN_PROTOCOL:-udp}
      - OPENVPN_PORT=${OPENVPN_PORT:-1194}
      - VPN_NETWORK=${VPN_NETWORK:-10.8.0.0}
      - VPN_SERVER_IP=${VPN_SERVER_IP:-10.8.0.1}
      - VPN_DOMAIN=${VPN_DOMAIN:-vpn.example.com}
      - ALLOW_DUPLICATE_CN=${ALLOW_DUPLICATE_CN:-false}
    privileged: true
    networks:
      - openvpn-network

networks:
  openvpn-network:
    driver: bridge

volumes:
  openvpn-data:
    name: openvpn-data
    driver: local